spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: coderslab //install or coderslab
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

